### ISSUE TITLE
[Enhancement] Gexp command and xp command

### ISSUE THREAD

**Issue by NotSure21** [xMdb/hypixel-guild-chat-bot#22]
checks to see the Gexp for the week.
checks to see how much gexp for the day/week

**Comment by xMdb** [comment]
I won't be adding this because it is not worth my time as a junior developer to figure out all the steps required for this when others do it better. An example is Statsify (https://statsify.net/). Although, if you have the time to develop it yourself, feel free to open a pull request and I'd be glad to add it. Sorry about that.
